name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: "Erick-Hebert"  # Substitua pelo seu usuário do GitHub
          outputs: "github-snake.svg"
      
      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: github-snake.svg
  
